name       : pyswisseph
version    : '2.00.00'
release    : 2
source     :
    - https://pypi.python.org/packages/09/27/10ad652fa0e07fc89890142a6f900725e26cf02a24d8fd724015e08707b5/pyswisseph-2.00.00-2.tar.bz2 : 7b47f54a61ac17863a4d9e75269e53e09ad525780ac731eed6923415caa725cc
license    : GPL-2.0
component  : programming.python
summary    : Python extension to the Swiss Ephemeris
description: |
    Python extension to the Swiss Ephemeris
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
