name       : pyswisseph
version    : 2.00.00
release    : 5
source     :
    - https://pypi.python.org/packages/source/p/pyswisseph/pyswisseph-2.00.00-2.tar.bz2 : 7b47f54a61ac17863a4d9e75269e53e09ad525780ac731eed6923415caa725cc
license    : GPL-2.0-or-later
component  : programming.python
summary    : Python extension to the Swiss Ephemeris
description: |
    Python extension to the Swiss Ephemeris
builddeps  :
    - pkgconfig(python3)
setup      : |
    %python3_setup
install    : |
    %python3_install
