name       : pyswisseph
version    : 2.08.00
release    : 8
source     :
    - https://pypi.python.org/packages/source/p/pyswisseph/pyswisseph-2.08.00-1.tar.gz : 6b4818c0224d309c0b01f3c52df2432900dddcde345364408d99eafc9cdd1e71
license    : GPL-2.0-or-later
component  : programming.python
summary    : Python extension to the Swiss Ephemeris
description: |
    Python extension to the Swiss Ephemeris
builddeps  :
    - pkgconfig(python3)
setup      : |
    %python3_setup
install    : |
    %python3_install
